services:
  - type: web
    name: analisador-movimento-esportivo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.web_app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
    autoDeploy: true
